update ddgsearch

diff --git a/ddgsearch b/ddgsearch
--- a/ddgsearch
+++ b/ddgsearch
@@ -50,14 +50,10 @@ openurl() {
   local browser
   case "$url" in
     *youtube.com*|*youtu.be*|*vimeo.com*)
-      browser=$(select_from \
-        mpv mplayer2 mplayer) ;;
+      browser=$(select_from mpv mplayer2 mplayer) ;;
     *)
-      browser=$(select_from \
-        -c "pgrep -u $USER -i" \
-        firefox chromium-browser chrome)
-      [[ ! $browser ]] && browser='w3m'
-      ;;
+      browser=$(select_from -c "pgrep -u $USER -i" firefox chromium-browser chrome)
+      [[ -z $browser ]] && browser='w3m' ;;
   esac
   $browser "$url"
 }
@@ -69,11 +65,9 @@ if [[ -z "$*" ]]; then
 fi
 
 response=$( ddgr --json --noprompt --expand "$*" ) || die 'error connecting to DuckDuckGo, check connection'
-json=$( jq -c '. | map("\(.url) | \(.title) | \(.abstract)") | .[]' <<< "$response" ) || die 'error parsing results :('
-url=$( fzf -e --ansi --cycle --inline-info --select-1 <\
-  <( sed -r 's/<[^>]*>//g; s/\\n//g; s/^\s*"//; s/",?$//' <<< "$json" ) |
-  cut -d' ' -f1 )
+json=$(jq -rc '. | map("\(.url)\t\(.title) - \(.abstract)") | .[]' <<< "$response") || die 'error parsing results :('
+url=$(fzf -e --ansi --cycle --inline-info --select-1 --with-nth=2.. <<< "$json" | awk '{print $1}')
 
-if [[ -n "$url" ]]; then
+if [[ -n $url ]]; then
   openurl "$url"
 fi
